apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azureblob
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
    - name: accountName
      value: "stiat7lxif"
    - name: containerName
      value: "testcontainer"
    - name: azureTenantId
      value: "env:AZURE_TENANT_ID"